# Generated by Django 5.1.1 on 2024-11-21 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('cod', models.CharField(max_length=2)),
                ('indicative', models.CharField(max_length=10)),
                ('active', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idModule', models.IntegerField()),
                ('codModule', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdministratorLogs',
            fields=[
                ('administrator', models.OneToOneField(db_column='administrator_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.administrator')),
                ('datalog', models.DateTimeField(auto_now_add=True)),
                ('logfile', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrator_logs',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.products')),
            ],
            options={
                'db_table': 'product_stock',
            },
        ),
        migrations.CreateModel(
            name='AdministratorModules',
            fields=[
                ('administrator', models.ForeignKey(db_column='administrator_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.administrator')),
                ('pView', models.PositiveSmallIntegerField(null=True)),
                ('pInsert', models.PositiveSmallIntegerField(null=True)),
                ('pUpdate', models.PositiveSmallIntegerField(null=True)),
                ('pDelete', models.PositiveSmallIntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.modules')),
            ],
            options={
                'db_table': 'administrator_modules',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.products')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.size')),
            ],
            options={
                'db_table': 'product_size',
            },
        ),
    ]
