# Generated by Django 5.1.4 on 2025-02-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_movements_quantity_alter_stockproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movements',
            name='movement_type',
        ),
        migrations.AddField(
            model_name='movements',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stocks.stockproduct'),
        ),
        migrations.AlterField(
            model_name='movements',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
