# Generated by Django 5.1.1 on 2024-10-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock_product',
            table='stock_product',
        ),
    ]
