# Generated by Django 5.1.1 on 2024-10-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_produto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='produtos',
        ),
    ]
