# Generated by Django 5.1.1 on 2024-12-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_suppliercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='supplier_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.suppliercategory')),
            ],
            options={
                'db_table': 'supplier_type',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('nif', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(db_column='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.countries')),
                ('suppliertype', models.ForeignKey(db_column='supplier_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.suppliertype')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
