# Generated by Django 5.1.1 on 2024-11-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_stock_product_stockproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproduct',
            old_name='product',
            new_name='products',
        ),
    ]
