# Generated by Django 5.1.1 on 2024-12-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_suppliertype_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLogs',
            fields=[
                ('supplier', models.OneToOneField(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.supplier')),
                ('datalog', models.DateTimeField(auto_now_add=True)),
                ('logfile', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supplier_logs',
            },
        ),
        migrations.CreateModel(
            name='SupplierAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('address', models.CharField(max_length=200)),
                ('postalcode', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='stocks.countries')),
                ('supplier', models.ForeignKey(db_column='supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.supplier')),
            ],
            options={
                'db_table': 'supplier_address',
            },
        ),
    ]
