# Generated by Django 5.1.4 on 2025-02-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
