# Generated by Django 5.1.1 on 2024-12-05 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_supplierlogs_supplieradress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('closed', models.PositiveSmallIntegerField(choices=[(0, 'Closed'), (1, 'Active')], default=1)),
                ('totalvalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='stocks.supplier')),
            ],
            options={
                'db_table': 'order_supplier',
            },
        ),
    ]
