# Generated by Django 5.1.1 on 2024-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_rename_product_stockproduct_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idModule', models.IntegerField()),
                ('codModule', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=250)),
            ],
        ),
    ]
