# Generated by Django 5.1.1 on 2024-12-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_ordersupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSupplierProduct',
            fields=[
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.orderclient')),
                ('productvalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productref', models.CharField(max_length=50)),
                ('productsize', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=5, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='stocks.products')),
            ],
            options={
                'db_table': 'order_supplier_product',
            },
        ),
    ]
