# Generated by Django 5.1.1 on 2024-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_modules'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modules',
            table='modules',
        ),
    ]
