# Generated by Django 5.1.1 on 2024-11-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_clienttype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clienttype',
            table='client_type',
        ),
    ]
