# Generated by Django 5.1.1 on 2024-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_rename_products_stockproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
    ]
