# Generated by Django 5.1.1 on 2024-11-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttype',
            name='category',
            field=models.ForeignKey(db_column='client_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.clientcategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(db_column='product_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.productcategory'),
        ),
    ]
