# Generated by Django 5.1.1 on 2024-11-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorLogs',
            fields=[
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stocks', serialize=False, to='stocks.administrator')),
                ('datalog', models.DateTimeField(auto_now_add=True)),
                ('logfile', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrator_logs',
            },
        ),
    ]
