# Generated by Django 5.1.1 on 2024-11-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
