# Generated by Django 5.1.1 on 2024-11-18 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_alter_administratorlogs_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorModules',
            fields=[
                ('administrator', models.OneToOneField(db_column='idAdministrator', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.administrator')),
                ('pView', models.PositiveSmallIntegerField(null=True)),
                ('pInsert', models.PositiveSmallIntegerField(null=True)),
                ('pUpdate', models.PositiveSmallIntegerField(null=True)),
                ('pDelete', models.PositiveSmallIntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.modules')),
            ],
            options={
                'db_table': 'administrator_modules',
            },
        ),
    ]
