# Generated by Django 5.1.1 on 2024-11-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_clientaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientaddress',
            table='client_address',
        ),
    ]
