# Generated by Django 5.1.1 on 2024-11-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_size_productsize'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productsize',
            table='product_size',
        ),
    ]
