# Generated by Django 5.1.1 on 2024-11-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_alter_productsize_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratormodules',
            name='administrator',
            field=models.ForeignKey(db_column='administrator_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.administrator'),
        ),
    ]
